animations:
 cheer:
  name: GF Cheer
 singLEFT:
  name: GF left note
  y: -19
 singRIGHT:
  name: GF Right Note
  y: -20
 singUP:
  name: GF Up Note
  y: 4
 singDOWN:
  name: GF Down Note
  y: -20
 sad:
  name: gf sad
  x: -2
  y: -2
  indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
 danceLeft:
  name: GF Dancing Beat
  y: -9
  indices: [30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
 danceRight:
  name: GF Dancing Beat
  y: -9
  indices: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
 hairBlow:
  name: GF Dancing Beat Hair blowing
  x: 45
  y: -8
  indices: [0, 1, 2, 3]
 hairFall:
  name: GF Dancing Beat Hair Landing
  y: -9
  indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
 scared:
  name: GF FEAR
  x: -2
  y: -17